version: '3'

services:
  nginx_test:
    image: nginx:stable-alpine
    container_name: nginx_test
    ports:
      - "92:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_test
      - mysql_test2
    networks:
      - laravel

  mysql_test2:
    image: mysql:5.7.22
    container_name: mysql_test2
    restart: unless-stopped
    tty: true
    volumes:
     - /home/dix/DB/test3:/var/lib/mysql
    ports:
      - "3393:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: ajadam
      MYSQL_ROOT_PASSWORD: ajadam
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php_test:
    container_name: php_test
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    tty: true
    environment:
      XDEBUG_CONFIG: "remote_host=198.168.220.1"
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - mysql_test2
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 199.168.222.0/28
